name: Protobuf Build Warning
on:
  workflow_dispatch:
  pull_request:
jobs:
  protoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: Install Protoc
        run: |
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v3.19.2/protoc-3.19.2-linux-x86_64.zip
          unzip protoc-3.19.2-linux-x86_64.zip -d $HOME/.local
          export PATH="$PATH:$HOME/.local/bin"
      - name: Protoc Build
        run: |
          WARNING_MESSAGE=$(make - build.protoc 2>&1)
          if [[ "$WARNING_MESSAGE" =~ "warning" ]]; then
            echo $WARNING_MESSAGE
            exit 1
          else
            echo "not found"
            exit 0
          fi
