name: Protobuf Build Warning
on:
  workflow_dispatch:
jobs:
  protoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.19.4'
      - name: Protoc Build
        run: |
          ls -al
          protoc --version
