name: Protobuf Build Warning
on:
  workflow_dispatch:
jobs:
  protoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: Install Protoc
        run: |
          curl -LO $https://github.com/protocolbuffers/protobuf/releases/download/v3.19.2/protoc-3.19.2-osx-x86_64.zip
          unzip protoc-3.19.2-osx-x86_64.zip -d $HOME/.local
          export PATH="$PATH:$HOME/.local/bin"
      - name: Protoc Build
        run: |
          ls -al
          protoc --version
